dubbo:
  application:
    name: springboot-provider
  registry:
    protocol: zookeeper
    port: 2181
    address: 127.0.0.1
  protocol:
      name: dubbo
      port: 20880
#  monitor:
#    protocol: registry