dubbo:
  application:
    name: springboot-consumer
  registry:
    protocol: zookeeper
    port: 2181
    address: 127.0.0.1
    check: false
#  monitor:
#    protocol: registry
  consumer:
    check: false
server:
  port: 8085